//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squid_Deploy.TentacleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TentacleService.ITentacleService")]
    public interface ITentacleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITentacleService/RunTfsToEnv", ReplyAction="http://tempuri.org/ITentacleService/RunTfsToEnvResponse")]
        string RunTfsToEnv(string folder, string environmet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITentacleService/RunTfsToEnv", ReplyAction="http://tempuri.org/ITentacleService/RunTfsToEnvResponse")]
        System.Threading.Tasks.Task<string> RunTfsToEnvAsync(string folder, string environmet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITentacleServiceChannel : Squid_Deploy.TentacleService.ITentacleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TentacleServiceClient : System.ServiceModel.ClientBase<Squid_Deploy.TentacleService.ITentacleService>, Squid_Deploy.TentacleService.ITentacleService {
        
        public TentacleServiceClient() {
        }
        
        public TentacleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TentacleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TentacleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TentacleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RunTfsToEnv(string folder, string environmet) {
            return base.Channel.RunTfsToEnv(folder, environmet);
        }
        
        public System.Threading.Tasks.Task<string> RunTfsToEnvAsync(string folder, string environmet) {
            return base.Channel.RunTfsToEnvAsync(folder, environmet);
        }
    }
}
